[Eth]
NetworkId = 76
SyncMode = "fast"
LightPeers = 20
DatabaseCache = 128
GasPrice = 20000000000
EthashCacheDir = "ethash"
EthashCachesInMem = 2
EthashCachesOnDisk = 3
EthashDatasetDir = "/home/jbrown/.ethash"
EthashDatasetsInMem = 1
EthashDatasetsOnDisk = 2
EnablePreimageRecording = false

[Eth.GPO]
Blocks = 10
Percentile = 50

[Node]
DataDir = "/home/jbrown/.link-geth"
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8645
HTTPModules = ["net", "web3", "eth"]
WSPort = 8646
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
DiscoveryV5Addr = ":30314"
BootstrapNodes = []
StaticNodes = ["enode://dce8ff1ae7ff6d1e7dbcd042071e0f95f50a6376054af45c23702e0397954d43b1afa0921e0e0eb87799c849f94162851696550bbc4b8bb1073b876d28f6c97f@139.162.15.124:30313"]
TrustedNodes = []
ListenAddr = ":30313"
